kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: datapower-operator-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: datapower-operator-{{ .Release.Namespace }}
    app.kubernetes.io/name: datapower-operator-{{ .Release.Namespace }}
    app.kubernetes.io/managed-by: datapower-operator
subjects:
- kind: ServiceAccount
  name: datapower-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: datapower-operator-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
